/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  -Tiago
 * Created: 10/11/2016
 */

create table Livros (id integer generated by default as identity primary key, 
                    titulo varchar(255),
                    autor varchar(255),
                    data date;
);

